"""Study 3 grading. Local only, no model calls.
Reads phase2-result.json and phase3-result.json in this folder, the W1 meta files, the frozen truth,
and the W0 baseline, and writes RESULTS.md plus reads/*.json and checklist/*.json.
"""
import json, os, glob

HERE = os.path.dirname(os.path.abspath(__file__))
COH = os.path.join(HERE, "..", "coherence-2026-10-06")
truth = json.load(open(os.path.join(COH, "inputs", "dataset.json")))["truth"]
ORDER = ["electrical", "concrete", "metallurgy", "xylem", "ballast", "metamorphosis", "treatment", "rag", "lagrangian", "goodhart"]

def grade(run, resting, raised):
    if not run: return {"available": False}
    norm = lambda s: str(s or "").strip().lower()
    n, e = norm(resting), norm(raised)
    def ms(s):
        x = norm(s)
        if x == n: return "NORMAL"
        if x == e: return "ELEVATED"
        for w, lab in (sorted([(n, "NORMAL"), (e, "ELEVATED")], key=lambda t: -len(t[0]))):
            if w and w in x: return lab
        return "UNMAPPED:" + str(s)
    finalOk = run.get("finalQuantities") == truth["final"]
    modes = [ms(s) for s in run.get("finalStates", [])]
    modesOk = modes == truth["modes"]
    chg = sorted("|".join(map(str, [c["period"], c["position"], ms(c["from"]), ms(c["to"])])) for c in run.get("stateChanges", []))
    tchg = sorted("|".join(map(str, c)) for c in truth["changes"])
    changesOk = chg == tchg
    purgesOk = sorted(run.get("resetPeriods", [])) == sorted(truth["purges"])
    lostOk = run.get("lossTotal") == truth["lost"]
    return {"available": True, "exact": all([finalOk, modesOk, changesOk, purgesOk, lostOk]),
            "finalOk": finalOk, "modesOk": modesOk, "changesOk": changesOk, "purgesOk": purgesOk, "lostOk": lostOk,
            "got": {"final": run.get("finalQuantities"), "modes": modes, "resetPeriods": run.get("resetPeriods"), "loss": run.get("lossTotal")},
            "missingChanges": [x for x in tchg if x not in chg], "extraChanges": [x for x in chg if x not in tchg],
            "openPoints": len(run.get("openPoints", [])), "usedScript": run.get("usedScript")}

out = []
# ---------------- phase 2
p2 = json.load(open(os.path.join(HERE, "phase2-result.json"), encoding="utf-8"))
reads = []
for r in p2["reads"]:
    meta = json.load(open(os.path.join(HERE, "w1-write-ups", f"{r['key']}.meta.json")))
    g = grade(r["run"], meta["restingStateWord"], meta["raisedStateWord"])
    rec = {"key": r["key"], "n": r["n"], "run": r["run"], "grade": g, "source": "opus-5.5"}
    json.dump(rec, open(os.path.join(HERE, "reads", f"{r['key']}-{r['n']}.json"), "w", encoding="utf-8", newline="\n"), indent=1)
    reads.append(rec)
exact = sum(1 for r in reads if r["grade"].get("exact"))
out.append("# Study 3 results\n")
out.append(f"Generated by grade.py. Truth from inputs/dataset.json. Every read graded on all five fields.\n")
out.append("## Phase 2: reads of the disciplined write-ups (W1)\n")
out.append("| Domain | Read | Exact | Quantities | States | Changes | Resets | Loss | Open points | Script |")
out.append("|---|---|---|---|---|---|---|---|---|---|")
for k in ORDER:
    for r in sorted([x for x in reads if x["key"] == k], key=lambda x: x["n"]):
        g = r["grade"]
        if not g["available"]:
            out.append(f"| {k} | {r['n']} | no result | | | | | | | |"); continue
        yn = lambda b: "yes" if b else "**no**"
        out.append(f"| {k} | {r['n']} | {'**exact**' if g['exact'] else '**WRONG**'} | {yn(g['finalOk'])} | {yn(g['modesOk'])} | {yn(g['changesOk'])} | {yn(g['purgesOk'])} | {yn(g['lostOk'])} | {g['openPoints']} | {g['usedScript']} |")
out.append(f"\n**W1: {exact} of {len(reads)} reads exact.** Baseline W0 (same prompt, same model, undisciplined write-ups): 25 of 30, failures in metallurgy (3 of 3) and metamorphosis (2 of 3), one cause.\n")
wrong = [r for r in reads if r["grade"].get("available") and not r["grade"]["exact"]]
if wrong:
    out.append("### Wrong reads, with the reader's own account\n")
    for r in wrong:
        g = r["grade"]
        out.append(f"**{r['key']} read {r['n']}.** Got final {g['got']['final']}, resets {g['got']['resetPeriods']}, loss {g['got']['loss']}; missing changes {g['missingChanges']}; extra {g['extraChanges']}.")
        out.append("Open points: " + "; ".join(f"{o['point']} → {o['assumption']}" for o in r["run"].get("openPoints", [])))
        out.append("Notes: " + (r["run"].get("notes") or "")[:600] + "\n")
else:
    out.append("No wrong reads.\n")

# ---------------- phase 3
p3path = os.path.join(HERE, "phase3-result.json")
if os.path.exists(p3path):
    p3 = json.load(open(p3path, encoding="utf-8"))
    rules = json.load(open(os.path.join(HERE, "rule-checklist.json")))["rules"]
    table = {}
    for e in p3["extractions"]:
        json.dump(e, open(os.path.join(HERE, "checklist", f"{e['arm']}-{e['key']}.json"), "w", encoding="utf-8", newline="\n"), indent=1)
        table[(e["arm"], e["key"])] = e
    out.append("## Phase 3: rules recoverable from the write-up alone (fixed 23-rule checklist, Sonnet extractor, same instrument on both arms)\n")
    out.append("| Domain | W0 recoverable | W1 recoverable | Change |")
    out.append("|---|---|---|---|")
    tot0 = tot1 = 0
    for k in ORDER:
        a = table.get(("W0", k)); b = table.get(("W1", k))
        r0 = a["recoverable"] if a and a["recoverable"] is not None else None
        r1 = b["recoverable"] if b and b["recoverable"] is not None else None
        if r0 is not None: tot0 += r0
        if r1 is not None: tot1 += r1
        out.append(f"| {k} | {r0 if r0 is not None else 'none'}/23 | {r1 if r1 is not None else 'none'}/23 | {('+' if (r1 or 0) - (r0 or 0) >= 0 else '') + str((r1 or 0) - (r0 or 0)) if r0 is not None and r1 is not None else ''} |")
    out.append(f"| **total** | **{tot0}/230** | **{tot1}/230** | **{'+' if tot1 - tot0 >= 0 else ''}{tot1 - tot0}** |\n")
    # which rules were most often lost, per arm
    out.append("### Rules most often not recoverable\n")
    out.append("| Rule | W0 write-ups lacking it | W1 write-ups lacking it |")
    out.append("|---|---|---|")
    for rule in rules:
        l0 = sum(1 for k in ORDER if ("W0", k) in table and table[("W0", k)]["results"] and not next(x for x in table[("W0", k)]["results"] if x["id"] == rule["id"])["recoverable"])
        l1 = sum(1 for k in ORDER if ("W1", k) in table and table[("W1", k)]["results"] and not next(x for x in table[("W1", k)]["results"] if x["id"] == rule["id"])["recoverable"])
        if l0 or l1:
            out.append(f"| {rule['id']} {rule['rule'][:90]} | {l0} | {l1} |")
    out.append("\nThe extractor is a model reading with a fixed list; it is the same instrument on both arms, not a deterministic measure.\n")

open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print(f"W1 reads exact: {exact} of {len(reads)}")
for r in wrong: print("WRONG:", r["key"], r["n"], r["grade"]["got"])
