import json
spec = open("plain-spec.md", encoding="utf-8").read()
d = json.load(open("dataset.json"))

domains = [
 {"key": "electrical", "label": "the charge-stage chain (electrical)", "control": True,
  "mapping": "Six charge-storage stages in a chain (stage 1 at the source end, stage 6 at the load end). Quantity: units of stored charge. Capacity: a stage's rated charge. Spill-over: a breakdown shunt that passes excess charge to the next stage down the chain, handled stage by stage from 1 to 6; excess from stage 6 goes to ground. The two states: a comparator with hysteresis (a Schmitt trigger) that is ASSERTED or RELEASED; it asserts at the upper threshold and releases only at the lower one. Release step: a released stage leaks a quarter of its charge to ground; an asserted stage feeds back half of its charge to the previous stage through a return diode, computed from all stages' readings before any is changed. Global reset: a breaker trip that halves every stage, the removed charge going to ground. Loss tally: total charge sent to ground."},
 {"key": "concrete", "label": "the pour line (concrete)",
  "mapping": "Six pour forms along a chute, form 1 nearest the hopper, form 6 at the end. Quantity: units of mix in the form. Capacity: the form's volume. Spill-over: overtopping runs down the chute into the next form, handled form by form from 1 to 6; overtop from form 6 goes to the waste pit. The two states: a form is GREEN or HOT (HOT set by the upper mark, back to GREEN only at the lower mark; by rule a HOT form can go back to GREEN). Release step: a GREEN form loses a quarter of its mix to evaporation (waste); a HOT form bleeds back half of its mix up the chute into the previous form, all amounts figured from the forms' contents before any is changed. Global reset: a washout that halves every form, the removed mix going to waste. Loss tally: total to waste."},
 {"key": "metallurgy", "label": "the crucible cascade (metallurgy)",
  "mapping": "Six crucibles in a cascade, crucible 1 at the charging end, crucible 6 at the tapping end. Quantity: units of melt. Capacity: the crucible's working volume. Spill-over: overflow runs down a launder into the next crucible, handled one crucible at a time from 1 to 6; overflow from crucible 6 goes to the slag pit. The two states: BASE or SUPERHEATED (enters SUPERHEATED at the upper mark, returns to BASE only at the lower mark; by rule the return happens). Release step: a BASE crucible loses a quarter of its melt to slag; a SUPERHEATED crucible sends half of its melt back up a return launder into the previous crucible, all amounts figured from the crucibles' contents before any is changed. Global reset: an emergency tap that halves every crucible, the removed melt going to slag. Loss tally: total to slag."},
 {"key": "xylem", "label": "the stem run (plant vascular)",
  "mapping": "Six stem segments from the root collar (segment 1) to the crown (segment 6). Quantity: units of sap. Capacity: the segment's holding volume. Spill-over: excess sap is pushed up the xylem into the next segment toward the crown, handled segment by segment from 1 to 6; excess from segment 6 is transpired away. The two states: QUIET or SINK-ACTIVE (becomes SINK-ACTIVE at the upper mark, back to QUIET only at the lower mark). Release step: a QUIET segment respires away a quarter of its sap; a SINK-ACTIVE segment sends half of its sap back down the phloem into the previous segment toward the root, all amounts figured from the segments' contents before any is changed. Global reset: a leaf-drop event that halves every segment, the removed sap transpired away. Loss tally: total transpired or respired away."},
 {"key": "ballast", "label": "the ballast run (buoyancy and cavitation)",
  "mapping": "Six ballast compartments from bow (compartment 1) to stern (compartment 6). Quantity: units of water. Capacity: the compartment's volume. Spill-over: overflow passes aft through a scupper into the next compartment, handled compartment by compartment from 1 to 6; overflow from compartment 6 goes overboard. The two states: a pump is LAMINAR or CAVITATING (cavitation begins at the upper inception level and ends only at the lower desinence level). Release step: a LAMINAR compartment pumps a quarter of its water overboard; a CAVITATING compartment backflows half of its water forward into the previous compartment, all amounts figured from the compartments' contents before any is changed. Global reset: an emergency blow that halves every compartment, the removed water going overboard. Loss tally: total overboard."},
 {"key": "metamorphosis", "label": "the rearing line (insect metamorphosis)",
  "mapping": "Six rearing chambers in a line, chamber 1 first, chamber 6 last. Quantity: units of nutrient mass. Capacity: the chamber's holding limit. Spill-over: excess is carried forward into the next chamber, handled chamber by chamber from 1 to 6; excess from chamber 6 is discarded. The two states: a chamber is LARVAL or PUPAL (enters PUPAL at the upper mark, returns to LARVAL only at the lower mark; by rule the return happens and is ordinary). Release step: a LARVAL chamber metabolises away a quarter of its mass; a PUPAL chamber reabsorbs half of its mass back into the previous chamber, all amounts figured from the chambers' contents before any is changed. Global reset: a moult that halves every chamber, the removed mass discarded. Loss tally: total discarded or metabolised."},
 {"key": "treatment", "label": "the treatment train (water and sewage treatment)",
  "mapping": "Six tanks in series, tank 1 at the inlet, tank 6 at the outfall. Quantity: units of liquor. Capacity: the tank's volume. Spill-over: overflow passes a weir into the next tank, handled tank by tank from 1 to 6; overflow from tank 6 goes to outfall. The two states: a tank is STEADY or OVERLOADED (becomes OVERLOADED at the upper mark, back to STEADY only at the lower mark). Release step: a STEADY tank discharges a quarter of its liquor to outfall; an OVERLOADED tank returns half of its liquor to the previous tank through the return line, all amounts figured from the tanks' contents before any is changed. Global reset: a storm bypass that halves every tank, the removed liquor going to outfall. Loss tally: total to outfall."},
 {"key": "rag", "label": "the retrieval tier stack (RAG architecture)",
  "mapping": "Six retrieval buffers in a stack, tier 1 closest to the model, tier 6 furthest. Quantity: chunks held. Capacity: the tier's chunk budget. Spill-over: over-budget chunks are evicted to the next tier out, handled tier by tier from 1 to 6; evictions from tier 6 are dropped. The two states: a tier is COLD or HOT (becomes HOT at the upper mark, back to COLD only at the lower mark). Release step: a COLD tier compacts away a quarter of its chunks (dropped); a HOT tier promotes half of its chunks back into the previous tier, all amounts figured from the tiers' contents before any is changed. Global reset: a context reset that halves every tier, the removed chunks dropped. Loss tally: total dropped."},
 {"key": "lagrangian", "label": "the constrained-state solver (linear algebra and Lagrangian optimisation)",
  "mapping": "A state vector x with six integer components, index 1 to 6. Quantity: the component value. Capacity: a box constraint c_i. Spill-over: a Gauss-Seidel-style sweep from component 1 to 6 that projects each component onto its box and adds the violation to the next component (not a simultaneous Jacobi projection); the violation of component 6 is added to a slack accumulator. The two states: each component has an active-set flag INACTIVE or ACTIVE with hysteresis (activates at the upper threshold, deactivates only at the lower threshold). Release step: a Jacobi-style simultaneous update computed from the current vector: an INACTIVE component sheds floor(x_i/4) to slack; an ACTIVE component moves floor(x_i/2) to component i-1 (component 1 sends it to slack). Global reset: a penalty step that halves every component (floor) when the 1-norm exceeds the budget, the removed amount going to slack. Loss tally: the slack accumulator."},
 {"key": "goodhart", "label": "the delivery pipeline (team metrics and Goodhart's law)",
  "mapping": "Six teams in a delivery pipeline, team 1 at intake, team 6 at the customer end. Quantity: open tickets. Capacity: the team's WIP limit. Spill-over: tickets over the limit are handed to the next team downstream, handled team by team from 1 to 6; overflow from team 6 is closed-without-action. The two states: a team is ROUTINE or ESCALATED (becomes ESCALATED at the upper mark, back to ROUTINE only at the lower mark). Release step: a ROUTINE team closes a quarter of its tickets; an ESCALATED team bounces half of its tickets back to the previous team, all amounts figured from the teams' counts before any is changed. Global reset: a quarterly backlog purge that halves every team when the total open count exceeds the target, the removed tickets closed-without-action. Loss tally: total closed (by any route). The target is just a number; the document must not add any gaming, incentive, or behavioural rule."},
]

args = {
    "plainSpec": spec,
    "dataset": {k: d[k] for k in ("C", "U", "D", "L0", "G", "INTAKE")},
    "truth": d["truth"],
    "domains": domains,
    "skillPath": r"C:\Users\USER\AppData\Local\Temp\om\coherence\desk-preread.md",
}
json.dump(args, open("args.json", "w"), indent=0)
print(len(json.dumps(args)), "chars")
